{
 "title": "Liteframe",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(actor_num,namespace)"
    }
   },
   { "name": "pod", "query": { "query": "label_values(actor_num,pod)" } }
  ]
 },
 "panels": [
  {
   "title": "gameserver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "玩家",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "user{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gameserver actor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "actor数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "actor_num{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "actor队列",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "actor_queue{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "mongodb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "db QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(dbCmdCost_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "db Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(dbCmdCost_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) / sum by(cmd) (rate(dbCmdCost_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "db P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(cmd, le) (rate(dbCmdCost_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "dbMsg QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(cmd) (rate(dbMsg{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  { "title": "rpc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "RPC QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(rpcid) (rate(rpcMsg{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{rpcid}}"
    }
   ]
  },
  {
   "title": "RPC Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(rpcid) (rate(rpcCost_sum{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) / sum by(rpcid) (rate(rpcCost_count{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{rpcid}}"
    }
   ]
  },
  {
   "title": "RPC P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(rpcid, le) (rate(rpcCost_bucket{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "{{rpcid}}"
    }
   ]
  },
  {
   "title": "RPC Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(rpcid) (rate(rpcSuccess_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) / (sum by(rpcid) (rate(rpcSuccess_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) + sum by(rpcid) (rate(rpcFail_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "{{rpcid}}"
    }
   ]
  },
  {
   "title": "RPC Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(rpcid) (rate(rpcFail_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) / (sum by(rpcid) (rate(rpcSuccess_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) + sum by(rpcid) (rate(rpcFail_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "{{rpcid}}"
    }
   ]
  }
 ]
}