{
 "title": "轻量化框架-Go Runtime",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_goroutines,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(go_goroutines{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "description": "Average total bytes of memory reserved across all process instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_memstats_sys_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} (avg)"
    }
   ]
  },
  {
   "title": "Stack Memory Use",
   "type": "timeseries",
   "description": "Average stack memory usage across all instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_memstats_stack_sys_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: stack inuse (avg)"
    }
   ]
  },
  {
   "title": "Other Memory Reservations",
   "type": "timeseries",
   "description": "Average memory reservations by the runtime, not for stack or heap, across all instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_memstats_mspan_sys_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: mspan (avg)"
    },
    {
     "expr": "avg by(pod)(go_memstats_mcache_sys_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: mcache (avg)"
    },
    {
     "expr": "avg by(pod)(go_memstats_buck_hash_sys_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: buck hash (avg)"
    },
    {
     "expr": "avg by(pod)(go_memstats_gc_sys_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: gc (avg)"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "description": "Average memory reserved, and actually in use, by the heap, across all instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_memstats_heap_sys_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: heap reserved (avg)"
    },
    {
     "expr": "avg by(pod)(go_memstats_heap_inuse_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: heap in use (avg)"
    },
    {
     "expr": "avg by(pod)(go_memstats_heap_alloc_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: heap alloc (avg)"
    },
    {
     "expr": "avg by(pod)(go_memstats_heap_idle_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: heap idle (avg)"
    },
    {
     "expr": "avg by(pod)(go_memstats_heap_released_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: heap released (avg)"
    }
   ]
  },
  {
   "title": "Allocation Rate, Bytes",
   "type": "timeseries",
   "description": "Average allocation rate in bytes per second, across all instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by(pod)(rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}: bytes malloced/s (avg)"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "timeseries",
   "description": "Average rate of heap object allocation, across all instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}: obj mallocs/s (avg)"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "Average number of live memory objects across all instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by(pod)(go_memstats_mallocs_total{namespace=~\"$namespace\", pod=~\"$pod\"} - go_memstats_frees_total{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: object count (avg)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Average number of goroutines across instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_goroutines{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: goroutine count (avg)"
    }
   ]
  },
  {
   "title": "GC min & max duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_gc_duration_seconds{quantile=\"0\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: min gc time (avg)"
    },
    {
     "expr": "avg by(pod)(go_gc_duration_seconds{quantile=\"1\", namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}: max gc time (avg)"
    }
   ]
  },
  {
   "title": "Next GC, Bytes",
   "type": "timeseries",
   "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a namespace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(pod)(go_memstats_next_gc_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}} next gc bytes (avg)"
    }
   ]
  }
 ]
}