{
 "title": "轻量化框架-Gateway",
 "tags": [
  "liteframe",
  "gateway"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(client,namespace)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(client{namespace=~\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "客户端连接", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "客户端连接/在线数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "client{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "服务器人数", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "各服务器在线人数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "server{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "server-{{serverId}}"
    }
   ]
  },
  { "title": "消息吞吐", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "接收消息 QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(id) (increase(rcvMsg{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "msg-{{id}}"
    }
   ]
  },
  {
   "title": "发送消息 QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(id) (increase(send{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "msg-{{id}}"
    }
   ]
  },
  {
   "title": "总吞吐量 QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(rcvMsg{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "接收总计"
    },
    {
     "expr": "sum(rate(send{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "发送总计"
    }
   ]
  }
 ]
}